version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - "3000:3000"
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /Users/dadaz/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my_template_typeorm
      - MYSQL_ROOT_PASSWORD=Ljb123456,
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      -  "6379:6379"
    volumes:
      - /Users/dadaz/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge